name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - uses: actions/checkout@v3
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.14.0"
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
